// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tisBJO4mY4xxcGQiM6K6l_EWp5tIdZI',
    appId: '1:458724976161:android:22872bf356d1d5d4a16560',
    messagingSenderId: '458724976161',
    projectId: 'cozzycruise-61c4b',
    storageBucket: 'cozzycruise-61c4b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5JYPFaZAqvuTpAQ5jHis3xmsVzWF-zo',
    appId: '1:458724976161:ios:b49eace2bcc9278ba16560',
    messagingSenderId: '458724976161',
    projectId: 'cozzycruise-61c4b',
    storageBucket: 'cozzycruise-61c4b.firebasestorage.app',
    iosClientId:
        '458724976161-uhtuhbvue536ncvlj65nmg2ahuj29i7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.cozzyCruise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX0zAsztm8VHTyczhnWn6jodqVzZmd1y8',
    appId: '1:458724976161:web:6bc806277c5ee6dda16560',
    messagingSenderId: '458724976161',
    projectId: 'cozzycruise-61c4b',
    authDomain: 'cozzycruise-61c4b.firebaseapp.com',
    storageBucket: 'cozzycruise-61c4b.firebasestorage.app',
    measurementId: 'G-746J503LVX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0zAsztm8VHTyczhnWn6jodqVzZmd1y8',
    authDomain: 'cozzycruise-61c4b.firebaseapp.com',
    projectId: 'cozzycruise-61c4b',
    storageBucket: 'cozzycruise-61c4b.firebasestorage.app',
    messagingSenderId: '458724976161',
    appId: '1:458724976161:web:52ba16a8d7886a39a16560',
    measurementId: 'G-XX02ZKJV76',
  );
}
